name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: ".tests/fire_test.py"
      id: tests-fire_test-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 10
        setup-command: pip install pytest json
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS-FIRE_TEST-PY_RESULTS: "${{steps.tests-fire_test-py.outputs.result}}"
      with:
        runners: tests-fire_test-py
